Repository getsentry/sentry-php, pull requests merged in 2019-03, with the labels that each got.

#783 feat: Update readme and Upgrade2.0
  README.md
  UPGRADE-2.0.md
  composer.json
Labels: Status: Confirmed, Type: Documentation

#786 fix: Mark Sentry internal frames for attach_stacktrace to in_app false
  CHANGELOG.md
  src/Stacktrace.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Improvement

#794 Fix documentation of error_types option
  UPGRADE-2.0.md
  src/Options.php
Labels: Status: Confirmed, Type: Bug, Type: Documentation

#791 improve breadcrumb coverage
  tests/BreadcrumbTest.php
Labels: Status: Confirmed, Type: Improvement
