Repository getsentry/sentry-php, pull requests merged in 2019-11, with the labels that each got.

#916 Suggest monolog
  CHANGELOG.md
  composer.json
Labels: Status: Confirmed, Type: Improvement

#917 Make the $errcontext argument of the ErrorHandler::handleError() method nullable
  CHANGELOG.md
  src/ErrorHandler.php
Labels: Status: Confirmed, Type: Bug

#894 Fix failing build on PHP 7.4
  .travis.yml
  composer.json
  tests/phpt/error_handler_respects_error_reporting.phpt
Labels: Status: Confirmed, Type: Improvement

#925 Symfony 5 compatibility
  composer.json
Labels: Status: Blocked, Status: Confirmed, Type: Improvement

#926 Ensure compatibility PHP 7.4 (cherry picked from #894)
  .travis.yml
  CHANGELOG.md
  composer.json
  tests/phpt/error_handler_respects_error_reporting.phpt
Labels: Status: Confirmed, Type: Improvement

#919 Make the `integrations` option accept a callable
  CHANGELOG.md
  src/ClientBuilder.php
  src/Integration/Handler.php
  src/Options.php
  src/Transport/NullTransport.php
  tests/OptionsTest.php
Labels: Status: Confirmed, Type: Improvement
