Repository getsentry/sentry-php, pull requests merged in 2019-02, with the labels that each got.

#760 Lower the default send_attempts option to 3
  src/Options.php
Labels: Status: Confirmed, Type: Improvement

#762 Error handler as singleton and with listeners
  .travis.yml
  UPGRADE-2.0.md
  src/ClientBuilder.php
  src/ErrorHandler.php
  src/Integration/ErrorHandlerIntegration.php
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  tests/ClientBuilderTest.php
  tests/ErrorHandlerTest.php
  tests/Fixtures/classes/StubErrorListener.php
  tests/Fixtures/classes/StubTransport.php
  tests/SdkTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Util/JSONTest.php
  tests/phpt/error_handler_called.phpt
  tests/phpt/error_handler_refuses_negative_value.phpt
  tests/phpt/error_handler_respects_captureAt.phpt
  tests/phpt/fatal_error.phpt
  tests/phpt/send_only_all_except_notice.phpt
Labels: Status: Confirmed, Type: Breaking, Type: Bug

#765 Add AppVeyor status badge
  README.md
Labels: Status: Confirmed, Type: Documentation

#743 Ensure context lines option is used (fixes #740)
  src/Options.php
  src/Stacktrace.php
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug

#769 Update changelog
  CHANGELOG.md
  UPGRADE-2.0.md
Labels: Type: Documentation

#768 Remove link to unmaintained Nette community integration
  README.md
Labels: Status: Confirmed, Type: Documentation

#752 Allow formatted message to be passed in event payload
  src/Context/Context.php
  src/Event.php
  src/EventFactory.php
  tests/EventFactoryTest.php
  tests/EventTest.php
Labels: Type: Feature

#770 Update gitattributes
  .gitattributes
Labels: Status: Confirmed, Type: Improvement

#774 Use mb_* functions to handle serialization and unicode file paths
  src/Serializer/AbstractSerializer.php
  src/Stacktrace.php
Labels: Status: Confirmed, Type: Bug

#776 ref: Make getScope private
  CHANGELOG.md
  src/State/Hub.php
  src/State/HubInterface.php
  tests/ClientTest.php
  tests/SdkTest.php
  tests/State/HubTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#778 Switch CI from nightly to 7.4snapshot
  .travis.yml
Labels: Status: Confirmed, Type: Improvement

#775 feat: Add http proxy option for curl client
  CHANGELOG.md
  UPGRADE-2.0.md
  src/ClientBuilder.php
  src/Options.php
  tests/ClientBuilderTest.php
  tests/OptionsTest.php
Labels: Status: Confirmed, Type: Feature

#785 Handle silenced errors gracefully
  CHANGELOG.md
  src/ErrorHandler.php
  src/Exception/SilencedErrorException.php
  src/Integration/ErrorListenerIntegration.php
  src/Options.php
  tests/OptionsTest.php
  tests/phpt/silenced_errors.phpt
Labels: Type: Bug, Type: Improvement
