Repository getsentry/sentry-php, pull requests merged in 2019-12, with the labels that each got.

#930 Fix PHP 7.4 deprecations
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  composer.json
  phpstan.neon
  src/Serializer/AbstractSerializer.php
  tests/Serializer/AbstractSerializerTest.php
Labels: Status: Confirmed, Type: Bug

#928 Add the IgnoreErrorsIntegration integration and deprecate the excluded_exceptions option
  CHANGELOG.md
  README.md
  phpstan.neon
  src/Client.php
  src/ClientInterface.php
  src/Integration/Handler.php
  src/Integration/IgnoreErrorsIntegration.php
  src/Options.php
  src/State/HubInterface.php
  tests/ClientTest.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
  tests/OptionsTest.php
  tests/SentrySdkExtension.php
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_captures_rethrown_exception_once.phpt
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/error_listener_integration_skips_fatal_errors_if_configured.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
  tests/phpt/spool_drain.phpt
Labels: Status: Confirmed, Type: Feature

#931 Allows merging user context on Scope::setUser()
  CHANGELOG.md
  src/State/Scope.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Improvement

#934 Fix error thrown when serializing an event containing invalid UTF-8 strings
  CHANGELOG.md
  composer.json
  phpstan.neon
  src/Transport/HttpTransport.php
  src/Util/JSON.php
  tests/Util/JSONTest.php
Labels: Status: Confirmed, Type: Bug

#938 Use Chocolatey to install PHP on AppVeyor to avoid broken download links
  .appveyor.yml
Labels: Status: Confirmed, Type: Improvement

#940 Fix Client::captureEvent not considering the attach_stacktrace option
  .appveyor.yml
  CHANGELOG.md
  src/Client.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Bug

#937 Use PECL uuid function
  CHANGELOG.md
  composer.json
  src/Event.php
  tests/EventTest.php
Labels: Status: Confirmed, Type: Improvement

#942 Add TYPO3 SDK integration package to the list of 3rd party vendors supporting SDK 2.x
  README.md
Labels: Status: Confirmed, Type: Documentation

#941 Support setting arbitrary contexts in the scope and event
  CHANGELOG.md
  src/Context/RuntimeContext.php
  src/Context/ServerOsContext.php
  src/Context/TagsContext.php
  src/Event.php
  src/State/Scope.php
  tests/EventTest.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Feature
