Repository getsentry/sentry-php, pull requests merged in 2019-10, with the labels that each got.

#892 Fix #891 by adding the errcontext argument
  CHANGELOG.md
  src/ErrorHandler.php
Labels: Status: Confirmed, Type: Bug

#890 Add support for Guzzle as default HTTP client
  phpstan.neon
  src/ClientBuilder.php
  src/State/HubAdapter.php
  tests/ClientBuilderTest.php
Labels: Status: Confirmed, Type: Feature

#874 Add 3rd party integrations
  README.md
Labels: Status: Confirmed, Type: Documentation

#821 Handle string callable in case of non-static method
  CHANGELOG.md
  src/Serializer/AbstractSerializer.php
  src/Stacktrace.php
  tests/Serializer/AbstractSerializerTest.php
Labels: Status: Confirmed, Type: Bug

#902 #901: Replace critical with fatal status
  CHANGELOG.md
  src/Breadcrumb.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Bug

#911 Fix frame inApp detection
  CHANGELOG.md
  src/Stacktrace.php
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug
