Repository getsentry/sentry-php, pull requests merged in 2019-08, with the labels that each got.

#860 added OXID eShop module to list of 3rd party integrations
  README.md
Labels: Status: Confirmed, Type: Documentation

#864 Do not set the transaction attribute of the event when in CLI
  CHANGELOG.md
  src/EventFactory.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
Labels: Status: Confirmed, Type: Bug

#861 Skip integrations not bound to the current client and fetch their options from it
  CHANGELOG.md
  src/ClientBuilder.php
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  src/Integration/FatalErrorListenerIntegration.php
  src/Integration/ModulesIntegration.php
  src/Integration/RequestIntegration.php
  src/State/Hub.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#813 Implement support for flushable clients
  CHANGELOG.md
  composer.json
  src/Client.php
  src/FlushableClientInterface.php
  src/Transport/ClosableTransportInterface.php
  src/Transport/HttpTransport.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/Transport/HttpTransportTest.php
Labels: Status: Confirmed, Type: Feature

#846 Update PHPStan to 0.11.x and add Psalm support
  .php_cs
  .travis.yml
  CHANGELOG.md
  README.md
  composer.json
  phpstan.neon
  psalm.xml.dist
  src/ClientBuilder.php
  src/ClientBuilderInterface.php
  src/Context/Context.php
  src/ErrorHandler.php
  src/Event.php
  src/EventFactory.php
  src/Exception/MissingProjectIdCredentialException.php
  src/Exception/MissingPublicKeyCredentialException.php
  src/HttpClient/Authentication/SentryAuthentication.php
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  src/Integration/Handler.php
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Serializer/RepresentationSerializer.php
  src/Serializer/RepresentationSerializerInterface.php
  src/Stacktrace.php
  src/State/Hub.php
  src/Transport/HttpTransport.php
  src/Transport/TransportInterface.php
  tests/ClientBuilderTest.php
  tests/Exception/MissingProjectIdCredentialExceptionTest.php
  tests/Exception/MissingPublicKeyCredentialExceptionTest.php
  tests/HttpClient/Authentication/SentryAuthenticationTest.php
  tests/Transport/HttpTransportTest.php
Labels: Status: Confirmed, Type: Improvement
