Repository getsentry/sentry-php, pull requests merged in 2019-07, with the labels that each got.

#843 Added support for setting transaction name via monolog extra context
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Status: Confirmed, Type: Improvement

#840 [Monolog] Add channel to payload as logger
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Status: Confirmed, Type: Improvement

#849 fix: parameter and return type of HubInterface
  CHANGELOG.md
  src/State/HubInterface.php
Labels: Status: Confirmed, Type: Improvement

#852 Add functions to clear breadcrumbs and bulk set tags and extras in the scope
  .php_cs
  CHANGELOG.md
  src/State/Hub.php
  src/State/Scope.php
  tests/Monolog/HandlerTest.php
  tests/SdkTest.php
  tests/State/HubTest.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Feature, Type: Improvement

#853 Revert extracting the transaction name from structured log data in Monolog handler
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Status: Confirmed, Type: Feature

#858 Allow numeric value in tags.
  CHANGELOG.md
  src/Context/Context.php
  src/Context/TagsContext.php
  tests/Context/TagsContextTest.php
Labels: Status: Confirmed, Type: Improvement

#857 Fix sending of GZIP-compressed requests when the enable_compression option is on
  .appveyor.yml
  CHANGELOG.md
  composer.json
  src/ClientBuilder.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  tests/ClientBuilderTest.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
Labels: Status: Confirmed, Type: Bug

#823 Fix undefined index generated by missing function in class
  src/Stacktrace.php
  tests/Fixtures/backtraces/anonymous_frame.json
  tests/Fixtures/backtraces/exception.json
  tests/Fixtures/frames/missing_function_key.json
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug
