Repository getsentry/sentry-php, pull requests merged in 2019-01, with the labels that each got.

#742 Add PHP 7.3 to Travis CI build and support EditorConfig
  .editorconfig
  .gitmodules
  .scrutinizer.yml
  .travis.yml
  src/ClientBuilder.php
  src/HttpClient/Authentication/SentryAuthentication.php
  tests/HttpClient/Authentication/SentryAuthenticationTest.php
  tests/SdkTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Util/JSONTest.php
Labels: Type: Improvement

#738 Update CHANGELOG and UPGRADE documents
  CHANGELOG.md
  UPGRADE-2.0.md
  src/Client.php
  src/Sdk.php
Labels: Type: Documentation

#744 Mention TYPO3 integration
  README.md
Labels: Type: Documentation

#747 Create necessary factories only when using HTTP transport
  src/ClientBuilder.php
Labels: Type: Improvement

#753 Remove unused 'serialize_all_object' option
  UPGRADE-2.0.md
  src/Options.php
Labels: Type: Improvement

#754 Remove unused option mb_detect_order
  src/Options.php
Labels: Type: Improvement

#745 feat: Add max_value_length option
  src/Client.php
  src/ClientBuilder.php
  src/EventFactory.php
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Stacktrace.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
  tests/OptionsTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Serializer/RepresentationSerializerTest.php
  tests/Serializer/SerializerTest.php
  tests/StacktraceTest.php
Labels: Type: Feature, Type: Improvement
