Repository getsentry/sentry-php, pull requests merged in 2019-09, with the labels that each got.

#877 GZIP-encode the request in memory instead of streaming
  CHANGELOG.md
  src/ClientBuilder.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
Labels: Status: Confirmed, Type: Bug

#865 Add an integration to set the transaction attribute of the event
  CHANGELOG.md
  composer.json
  phpstan.neon
  phpunit.xml.dist
  src/ClientBuilder.php
  src/EventFactory.php
  src/Integration/TransactionIntegration.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
  tests/Integration/TransactionIntegrationTest.php
  tests/SentrySdkExtension.php
Labels: Status: Confirmed, Type: Feature

#847 Deprecate the methods on the HubInterface to get and set the current hub
  .php_cs.dist
  CHANGELOG.md
  composer.json
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  src/Integration/FatalErrorListenerIntegration.php
  src/Integration/ModulesIntegration.php
  src/Integration/RequestIntegration.php
  src/Integration/TransactionIntegration.php
  src/SentrySdk.php
  src/State/Hub.php
  src/State/HubAdapter.php
  src/State/HubInterface.php
  src/functions.php
  tests/FunctionsTest.php
  tests/Integration/TransactionIntegrationTest.php
  tests/SentrySdkExtension.php
  tests/SentrySdkTest.php
  tests/Spool/MemorySpoolTest.php
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_captures_rethrown_exception_once.phpt
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/error_listener_integration_skips_fatal_errors_if_configured.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
  tests/phpt/spool_drain.phpt
Labels: Status: Confirmed, Type: Feature, Type: Improvement

#885 Disable the deprecation about delaying sending of events until shutdown
  src/ClientBuilder.php
Labels: Status: Confirmed, Type: Bug
