Repository getsentry/sentry-php, pull requests merged in 2019-04, with the labels that each got.

#792 Remap E_RECOVERABLE_ERROR to Severity::ERROR
  CHANGELOG.md
  src/Severity.php
  tests/SeverityTest.php
Labels: Status: Confirmed, Type: Improvement

#806 Fix #805: Default type must be an array
  src/Event.php
Labels: Status: Confirmed, Type: Bug

#810 Add support for SENTRY_ENVRIONMENT and SENTRY_RELEASE
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Improvement

#798 Add Breadcrumb::fromArray constructional helper function
  src/Breadcrumb.php
  tests/BreadcrumbTest.php
Labels: Status: Confirmed, Type: Improvement
