Repository getsentry/sentry-php, pull requests merged in 2019-05, with the labels that each got.

#808 Add Monolog handler
  CHANGELOG.md
  composer.json
  src/EventFactory.php
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Status: Confirmed, Type: Feature

#788 Make it possible to register fatal error listeners separately from the error listeners
  CHANGELOG.md
  phpunit.xml.dist
  src/ClientBuilder.php
  src/ErrorHandler.php
  src/Exception/FatalErrorException.php
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  src/Integration/FatalErrorListenerIntegration.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/ErrorHandlerTest.php
  tests/Fixtures/classes/CarelessException.php
  tests/Fixtures/classes/StubErrorListener.php
  tests/bootstrap.php
  tests/phpt/error_handler_called.phpt
  tests/phpt/error_handler_can_be_registered_once.phpt
  tests/phpt/error_handler_captures_error.phpt
  tests/phpt/error_handler_captures_exception.phpt
  tests/phpt/error_handler_captures_exception_thrown_from_previous_handler.phpt
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_captures_out_of_memory_fatal_error.phpt
  tests/phpt/error_handler_captures_rethrown_exception_once.phpt
  tests/phpt/error_handler_only_error_handler_registered.phpt
  tests/phpt/error_handler_only_exception_handler_registered.phpt
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_handler_returns_previous_error_handler_return_value.phpt
  tests/phpt/error_handler_throws_on_invalid_reserved_memory.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/error_listener_integration_skips_fatal_errors_if_configured.phpt
  tests/phpt/exception_rethrown.phpt
  tests/phpt/exception_thrown.phpt
  tests/phpt/fatal_error.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
  tests/phpt/fatal_error_not_captured_twice.phpt
  tests/phpt/out_of_memory.phpt
  tests/phpt/send_only_all_except_notice.phpt
  tests/phpt/silenced_errors.phpt
  tests/phpt/spool_drain.phpt
Labels: Status: Confirmed, Type: Feature, Type: Improvement

#807 Capture the body of the request and do a best effort to decode it
  CHANGELOG.md
  src/Exception/JsonException.php
  src/Integration/RequestIntegration.php
  src/Options.php
  src/Util/JSON.php
  tests/Integration/RequestIntegrationTest.php
  tests/OptionsTest.php
  tests/Util/JSONTest.php
Labels: Status: Confirmed, Type: Feature, Type: Improvement

#817 Fix code examples in upgrade to 2.0 doc
  UPGRADE-2.0.md
Labels: Status: Confirmed, Type: Documentation, Type: Improvement

#809 Implement class serializers and interface to customize how objects are serialized
  CHANGELOG.md
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Serializer/SerializableInterface.php
  tests/Serializer/SerializerTest.php
Labels: Type: Feature

#822 Change the behavior of excluded_exceptions option
  CHANGELOG.md
  src/Client.php
  src/EventFactory.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Bug, Type: Improvement
