Repository getsentry/sentry-php, pull requests merged in 2020-11, with the labels that each got.

#1123 Send stacktrace with events, not just exceptions
  CHANGELOG.md
  src/Serializer/PayloadSerializer.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Status: Confirmed, Type: Bug

#1119 Detect errors if a request body size is zero
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#1128 Update the README badges and fix the CI config to run on 2.x branch
  .appveyor.yml
  .travis.yml
  README.md
  phpstan.neon
Labels: Status: Confirmed, Type: Improvement

#1129 Fix capturing of the request body in the RequestIntegration integration when the stream is empty
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#1126 Add Scope::removeTag() method
  CHANGELOG.md
  src/State/Scope.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Feature

#1139 Fix regression introduced in #1119 that prevents capturing of the request body
  CHANGELOG.md
  composer.json
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#1143 Fix regression introduced in #1119 that prevents capturing of the request body
  CHANGELOG.md
  composer.json
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#1141 Migrate the error handling for the @ operator to php 8 state
  CHANGELOG.md
  src/ErrorHandler.php
Labels: Status: Confirmed, Type: Bug

#1144 Change the dependencies guzzlehttp/promises and symfony/options-resolver in favor of php 8 support
  CHANGELOG.md
  composer.json
Labels: Status: Confirmed, Type: Improvement

#1134 Deprecate SpanContext::fromTraceparent() and allow passing custom sampling context data to startTransaction()
  CHANGELOG.md
  composer.json
  phpstan.neon
  src/Dsn.php
  src/State/Hub.php
  src/State/HubAdapter.php
  src/State/HubInterface.php
  src/Tracing/SamplingContext.php
  src/Tracing/SpanContext.php
  src/Tracing/Transaction.php
  src/Tracing/TransactionContext.php
  src/functions.php
  tests/DsnTest.php
  tests/FunctionsTest.php
  tests/State/HubTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/TransactionContextTest.php
Labels: Status: Confirmed, Type: Feature
