Repository getsentry/sentry-php, pull requests merged in 2020-05, with the labels that each got.

#1003 Fix the context_lines option not skipping reading the source code if its value is set to null
  CHANGELOG.md
  src/Options.php
  src/Serializer/RepresentationSerializer.php
  src/Stacktrace.php
  tests/Integration/ModulesIntegrationTest.php
  tests/OptionsTest.php
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug

#1009 Update PHPStan to version 0.12
  composer.json
  phpstan.neon
  src/Breadcrumb.php
  src/Client.php
  src/ClientBuilderInterface.php
  src/ClientInterface.php
  src/Context/Context.php
  src/Context/RuntimeContext.php
  src/Context/ServerOsContext.php
  src/Context/TagsContext.php
  src/Context/UserContext.php
  src/ErrorHandler.php
  src/Event.php
  src/EventFactoryInterface.php
  src/Frame.php
  src/Integration/RequestIntegration.php
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Serializer/RepresentationSerializerInterface.php
  src/Serializer/SerializableInterface.php
  src/Serializer/SerializerInterface.php
  src/Stacktrace.php
  src/State/HubInterface.php
  src/State/Scope.php
  src/functions.php
  tests/ClientTest.php
  tests/Fixtures/classes/StubTransport.php
  tests/Fixtures/code/Latin1File.php
  tests/State/HubTest.php
Labels: Status: Confirmed, Type: Improvement

#1012 Allow to pass either a PSR-17 or a Httplug stream factory to the constructor of the GzipEncoderPlugin class
  CHANGELOG.md
  composer.json
  phpstan.neon
  src/HttpClient/HttpClientFactory.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
Labels: Status: Confirmed, Type: Improvement

#1013 Encapsulate the event ID into its own value object
  src/Event.php
  src/EventId.php
  src/Transport/HttpTransport.php
  src/Transport/NullTransport.php
  src/Transport/SpoolTransport.php
  tests/EventIdTest.php
  tests/EventTest.php
  tests/Transport/NullTransportTest.php
  tests/Transport/SpoolTransportTest.php
Labels: Status: Confirmed, Type: Feature

#1018 Fix BC break in Stacktrace::getSourceCodeExcerpt() method caused by #1003
  src/Stacktrace.php
Labels: Status: Confirmed, Type: Bug

#1011 Add the FrameContextifierIntegration integration
  CHANGELOG.md
  phpstan.neon
  src/Client.php
  src/Event.php
  src/EventFactory.php
  src/Frame.php
  src/Integration/FrameContextifierIntegration.php
  src/Options.php
  src/Stacktrace.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Integration/RequestIntegrationTest.php
  tests/OptionsTest.php
  tests/Serializer/SerializerTest.php
  tests/StacktraceTest.php
  tests/State/ScopeTest.php
Labels: Status: Confirmed, Type: Feature

#1016 Trim path from anonymous class
  CHANGELOG.md
  src/Stacktrace.php
  tests/Fixtures/backtraces/anonymous_frame_with_memory_address.json
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug

#1019 Incorrect Max Request Size Docblock
  src/Options.php
Labels: Status: Confirmed, Type: Documentation
