Repository getsentry/sentry-php, pull requests merged in 2020-01, with the labels that each got.

#945 Replace zendframework/zend-diactoros with guzzlehttp/psr7
  composer.json
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Improvement

#909 Add option to whitelist specific paths as 'in app'
  CHANGELOG.md
  src/Options.php
  src/Stacktrace.php
  tests/ClientTest.php
  tests/OptionsTest.php
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Feature

#951 Fix client creation with proxy
  CHANGELOG.md
  src/HttpClient/HttpClientFactory.php
Labels: Status: Confirmed, Type: Bug

#961 allow the stacktrace to be set to null
  CHANGELOG.md
  src/Event.php
  tests/EventTest.php
Labels: Status: Confirmed, Type: Bug

#960 do not auto-attach a backtrace when logging an exception
  CHANGELOG.md
  src/Client.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Bug

#956 Strip the memory address of the function from the frame of a stack trace
  CHANGELOG.md
  src/Stacktrace.php
  tests/Fixtures/backtraces/anonymous_frame_with_memory_address.json
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug

#958 Fixed check for exclude
  CHANGELOG.md
  src/Stacktrace.php
  tests/StacktraceTest.php
Labels: Status: Confirmed, Type: Bug
