Repository getsentry/sentry-php, pull requests merged in 2020-09, with the labels that each got.

#1078 Allow the user ID to be more types
  src/UserDataBag.php
  tests/UserDataBagTest.php
Labels: Status: Confirmed, Type: Bug

#1079 Remove the FlushableClientInterface and the ClosableTransportInterface interfaces
  CHANGELOG.md
  UPGRADE-3.0.md
  src/Client.php
  src/ClientInterface.php
  src/FlushableClientInterface.php
  src/Transport/ClosableTransportInterface.php
  src/Transport/HttpTransport.php
  src/Transport/NullTransport.php
  src/Transport/SpoolTransport.php
  src/Transport/TransportInterface.php
  tests/ClientTest.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/NullTransportTest.php
  tests/Transport/SpoolTransportTest.php
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/fatal_error_integration_captures_fatal_error.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
Labels: Status: Confirmed, Type: Breaking, Type: Deprecation, Type: Improvement

#1077 Extract the logic to serialize the event into an event serializer
  CHANGELOG.md
  UPGRADE-3.0.md
  composer.json
  src/Breadcrumb.php
  src/Client.php
  src/ClientBuilder.php
  src/Event.php
  src/EventFactory.php
  src/EventType.php
  src/Frame.php
  src/FrameBuilder.php
  src/Integration/FrameContextifierIntegration.php
  src/Serializer/PayloadSerializer.php
  src/Serializer/PayloadSerializerInterface.php
  src/Stacktrace.php
  src/State/Scope.php
  src/Tracing/Span.php
  src/Tracing/Transaction.php
  src/Transport/DefaultTransportFactory.php
  src/Transport/HttpTransport.php
  src/functions.php
  tests/BreadcrumbTest.php
  tests/EventFactoryTest.php
  tests/EventTest.php
  tests/FrameBuilderTest.php
  tests/FrameTest.php
  tests/HttpClient/HttpClientFactoryTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/StacktraceTest.php
  tests/State/ScopeTest.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TransactionTest.php
  tests/Transport/DefaultTransportFactoryTest.php
  tests/Transport/HttpTransportTest.php
  tests/bootstrap.php
Labels: Status: Confirmed, Type: Breaking, Type: Feature, Type: Improvement

#1080 Remove the SpoolTransport transport
  CHANGELOG.md
  UPGRADE-3.0.md
  src/Spool/MemorySpool.php
  src/Spool/SpoolInterface.php
  src/Transport/SpoolTransport.php
  tests/Spool/MemorySpoolTest.php
  tests/Transport/SpoolTransportTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Deprecation, Type: Improvement

#1083 feat: Add TracesSampler
  CHANGELOG.md
  src/Options.php
  src/State/Hub.php
  src/Tracing/SamplingContext.php
  tests/OptionsTest.php
  tests/Tracing/TransactionTest.php
Labels: Status: Confirmed, Type: Feature

#1084 Symfony HTTP client support
  CHANGELOG.md
  phpstan.neon
  src/HttpClient/HttpClientFactory.php
Labels: Status: Confirmed, Type: Feature

#1085 Add named constructors to the Event class
  CHANGELOG.md
  UPGRADE-3.0.md
  src/Event.php
  src/EventFactory.php
  src/Tracing/Transaction.php
  tests/EventTest.php
  tests/FunctionsTest.php
  tests/Integration/EnvironmentIntegrationTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
  tests/Integration/ModulesIntegrationTest.php
  tests/Integration/RequestIntegrationTest.php
  tests/Integration/TransactionIntegrationTest.php
  tests/Monolog/HandlerTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/State/HubTest.php
  tests/State/ScopeTest.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/NullTransportTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#1088 Update some deps and require at least PHP 7.2
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  composer.json
  src/Options.php
Labels: Status: Confirmed, Type: Improvement

#1086 Refactor the setup process of the integrations
  src/Client.php
  src/Integration/Handler.php
  src/Integration/IntegrationRegistry.php
  src/Options.php
  src/State/HubInterface.php
  src/functions.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/Integration/IntegrationRegistryTest.php
  tests/OptionsTest.php
  tests/SentrySdkExtension.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#1091 ref: Remove EventFactory
  composer.json
  src/Client.php
  src/ClientBuilder.php
  src/EventFactory.php
  src/EventFactoryInterface.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#1092 Polish the API related to APM
  src/Event.php
  src/Options.php
  src/ResponseStatus.php
  src/Serializer/PayloadSerializer.php
  src/State/Hub.php
  src/State/Scope.php
  src/Tracing/SamplingContext.php
  src/Tracing/Span.php
  src/Tracing/SpanContext.php
  src/Tracing/SpanId.php
  src/Tracing/SpanRecorder.php
  src/Tracing/SpanStatus.php
  src/Tracing/Transaction.php
  src/Tracing/TransactionContext.php
  tests/Serializer/PayloadSerializerTest.php
  tests/State/HubTest.php
  tests/Tracing/SamplingContextTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/SpanIdTest.php
  tests/Tracing/SpanRecorderTest.php
  tests/Tracing/SpanStatusTest.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TraceIdTest.php
  tests/Tracing/TransactionContextTest.php
  tests/Tracing/TransactionTest.php
Labels: Status: Confirmed, Type: Improvement

#1096 feat: Add guzzle http handler to create spans
  CHANGELOG.md
  src/Tracing/GuzzleTracingMiddleware.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Status: Confirmed, Type: Feature

#1098 Cleanup deprecated code
  phpstan.neon
  src/Serializer/AbstractSerializer.php
  src/Transport/NullTransport.php
  src/Util/JSON.php
  tests/Util/JSONTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#1099 fix: span vs transaction guzzle
  CHANGELOG.md
  src/Tracing/GuzzleTracingMiddleware.php
Labels: Status: Confirmed, Type: Bug

#1100 Add setter for value on ExceptionDataBag
  CHANGELOG.md
  src/ExceptionDataBag.php
Labels: Status: Confirmed, Type: Improvement
