Repository getsentry/sentry-php, pull requests merged in 2020-08, with the labels that each got.

#1055 Fix unreliable test comparing timestamps
  tests/EventTest.php
Labels: Type: Improvement

#1060 README: use composer from path
  README.md
Labels: Status: Confirmed, Type: Documentation, Type: Improvement

#1061 Fix IgnoreErrorsIntegration psalm type
  src/Integration/IgnoreErrorsIntegration.php
Labels: Status: Confirmed, Type: Documentation

#1064 Avoid capturing the request body in the RequestIntegration integration when the stream size is unknown
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Bug

#1063 Refactor the Stacktrace and Frame classes
  composer.json
  phpstan.neon
  src/Client.php
  src/Event.php
  src/EventFactory.php
  src/ExceptionDataBag.php
  src/ExceptionMechanism.php
  src/Frame.php
  src/FrameBuilder.php
  src/Integration/AbstractErrorListenerIntegration.php
  src/Integration/ErrorListenerIntegration.php
  src/Integration/ExceptionListenerIntegration.php
  src/Integration/FatalErrorListenerIntegration.php
  src/Integration/FrameContextifierIntegration.php
  src/Integration/IgnoreErrorsIntegration.php
  src/Stacktrace.php
  src/StacktraceBuilder.php
  src/Tracing/SpanContext.php
  tests/ClientTest.php
  tests/EventFactoryTest.php
  tests/EventTest.php
  tests/Fixtures/backtraces/anonymous_frame.json
  tests/Fixtures/backtraces/anonymous_frame_with_memory_address.json
  tests/Fixtures/backtraces/exception.json
  tests/Fixtures/frames/eval.json
  tests/Fixtures/frames/function.json
  tests/Fixtures/frames/missing_function_key.json
  tests/Fixtures/frames/runtime_created.json
  tests/FrameBuilderTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
  tests/StacktraceBuilderTest.php
  tests/StacktraceTest.php
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
Labels: Status: Confirmed, Type: Breaking, Type: Feature, Type: Improvement

#1066 Switch from Httplug HTTP factories to PSR-17 factories and return a promise from the transport
  CHANGELOG.md
  UPGRADE-3.0.md
  composer.json
  src/Client.php
  src/ClientBuilder.php
  src/HttpClient/HttpClientFactory.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  src/Response.php
  src/ResponseStatus.php
  src/Transport/DefaultTransportFactory.php
  src/Transport/HttpTransport.php
  src/Transport/NullTransport.php
  src/Transport/SpoolTransport.php
  src/Transport/TransportInterface.php
  tests/ClientTest.php
  tests/HttpClient/HttpClientFactoryTest.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
  tests/ResponseStatusTest.php
  tests/Transport/DefaultTransportFactoryTest.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/NullTransportTest.php
  tests/Transport/SpoolTransportTest.php
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_respects_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/fatal_error_integration_captures_fatal_error.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
  tests/phpt/http_transport_send_event_delayed.phpt
Labels: Status: Confirmed, Type: Breaking, Type: Feature, Type: Improvement

#1068 Cleanup the Monolog handler from deprecated features
  CHANGELOG.md
  UPGRADE-3.0.md
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#1072 Refactor the context classes
  CHANGELOG.md
  UPGRADE-3.0.md
  phpstan.neon
  src/Context/Context.php
  src/Context/OsContext.php
  src/Context/RuntimeContext.php
  src/Context/ServerOsContext.php
  src/Context/TagsContext.php
  src/Context/UserContext.php
  src/Event.php
  src/EventFactory.php
  src/Integration/EnvironmentIntegration.php
  src/Integration/RequestIntegration.php
  src/Options.php
  src/State/Scope.php
  src/Tracing/Span.php
  src/Tracing/Transaction.php
  src/UserDataBag.php
  src/Util/JSON.php
  src/Util/PHPVersion.php
  tests/ClientBuilderTest.php
  tests/Context/AbstractContextTest.php
  tests/Context/ContextTest.php
  tests/Context/OsContextTest.php
  tests/Context/RuntimeContextTest.php
  tests/Context/ServerOsContextTest.php
  tests/Context/TagsContextTest.php
  tests/Context/UserContextTest.php
  tests/EventFactoryTest.php
  tests/EventTest.php
  tests/FunctionsTest.php
  tests/Integration/EnvironmentIntegrationTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Integration/RequestIntegrationTest.php
  tests/Monolog/HandlerTest.php
  tests/OptionsTest.php
  tests/State/ScopeTest.php
  tests/UserDataBagTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Feature, Type: Improvement
