Repository getsentry/sentry-php, pull requests merged in 2021-01, with the labels that each got.

#1164 Add Yii2 integration
  README.md
Labels: Status: Confirmed, Type: Documentation

#1165 Fix the logger option not being applied to the event object
  CHANGELOG.md
  src/Client.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Bug

#1148 Dont overwrite Event properties
  CHANGELOG.md
  src/Client.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Bug

#1167 Deprecate the logger option
  CHANGELOG.md
  src/Client.php
  src/Options.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Status: Confirmed, Type: Deprecation

#1173 Fix broken build due to newly reported PHPStan errors
  phpstan-baseline.neon
  phpstan.neon
  src/EventHint.php
  tests/EventHintTest.php
Labels: Status: Confirmed, Type: Improvement

#1138 Allow passing the event hint to the captureException method and pass it down to the before_send callback
  CHANGELOG.md
  phpstan-baseline.neon
  src/Client.php
  src/ClientInterface.php
  src/Options.php
  src/State/Hub.php
  src/State/HubInterface.php
  src/functions.php
  tests/ClientTest.php
  tests/FunctionsTest.php
  tests/State/HubTest.php
Labels: Status: Confirmed, Type: Improvement

#1169 Fix default for client version
  src/Client.php
  src/ErrorHandler.php
  src/HttpClient/HttpClientFactory.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  src/Integration/RequestIntegration.php
  src/Options.php
  src/Severity.php
  src/Tracing/SpanContext.php
  src/UserDataBag.php
  src/Util/JSON.php
  src/Util/PHPVersion.php
  tests/ClientTest.php
  tests/FunctionsTest.php
  tests/HttpClient/HttpClientFactoryTest.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
  tests/Integration/RequestIntegrationTest.php
  tests/Serializer/SerializerTest.php
  tests/SeverityTest.php
  tests/Util/JSONTest.php
Labels: Status: Confirmed, Type: Bug

#1174 Deprecate the tags option
  CHANGELOG.md
  src/Client.php
  src/Options.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Status: Confirmed, Type: Deprecation

#1176 Add the $customSamplingContext argument to Hub::startTransaction() and HubAdapter::startTransaction()
  CHANGELOG.md
  src/State/Hub.php
  src/State/HubAdapter.php
  tests/State/HubAdapterTest.php
Labels: Status: Confirmed, Type: Improvement
