Repository getsentry/sentry-php, pull requests merged in 2021-02, with the labels that each got.

#1161 Filter PII rather than removing headers entirely
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Status: Confirmed, Type: Improvement

#1171 Allow jean85/pretty-package-versions 2.0 (backport of #1170)
  CHANGELOG.md
  Makefile
  composer.json
  src/Integration/ModulesIntegration.php
Labels: Status: Confirmed, Type: Improvement

#1170 Allow PrettyVersion 2.0
  CHANGELOG.md
  composer.json
  src/Integration/ModulesIntegration.php
Labels: Status: Confirmed, Type: Improvement

#1183 Fix incorrect detection of silenced errors (by the `@` operator)
  CHANGELOG.md
  phpstan-baseline.neon
  src/ErrorHandler.php
  tests/phpt/error_handler_captures_errors_not_silencable_on_php_8_and_up.phpt
  tests/phpt/error_handler_respects_capture_silenced_errors_option.phpt
  tests/phpt/error_handler_respects_error_types_option_regardless_of_error_reporting.phpt
Labels: Status: Confirmed, Type: Bug

#1181 Add a GitHub Action workflow to release a new version
  .github/workflows/publish-release.yaml
Labels: Status: Confirmed

#1188 Fix codecov warning due to too low fetch depth
  .craft.yml
  .editorconfig
  .github/workflows/ci.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
  codecov.yml
Labels: Status: Confirmed, Type: Improvement

#1116 Set the environment of the event to production if it has not been overridden explicitly
  CHANGELOG.md
  src/Client.php
  src/Event.php
  src/Options.php
  tests/ClientTest.php
Labels: Status: Confirmed, Type: Improvement
