Repository getsentry/sentry-php, pull requests merged in 2021-03, with the labels that each got.

#1191 Update list of 3rd party integrations
  README.md
Labels: Status: Confirmed, Type: Documentation

#1193 Allow populating breadcrumb timestamp with custom value
  CHANGELOG.md
  src/Breadcrumb.php
  tests/BreadcrumbTest.php
Labels: Status: Confirmed, Type: Improvement

#1200 Try to fix the CI build for PHP 8 + Windows
  tests/phpt/error_handler_captures_out_of_memory_fatal_error.phpt
Labels: Status: Confirmed, Type: Improvement

#1201 Add option to ignore errors from a specific tag
  CHANGELOG.md
  src/Integration/IgnoreErrorsIntegration.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
Labels: Status: Confirmed, Type: Feature

#1202 Fix random failing CI on Windows due to OOM error (port of #1200)
  tests/phpt/error_handler_captures_out_of_memory_fatal_error.phpt
Labels: Status: Confirmed, Type: Improvement

#1196 Fix `error_reporting` value not evaluated on the moment of the error being reported by default
  CHANGELOG.md
  src/Integration/ErrorListenerIntegration.php
  src/Options.php
  tests/OptionsTest.php
  tests/phpt/error_handler_respects_current_error_reporting_level.phpt
Labels: Status: Confirmed, Type: Bug
