Repository getsentry/sentry-php, pull requests merged in 2022-11, with the labels that each got.

#1419 add lordsimal/cakephp-sentry
  README.md
Labels: Type: Documentation, Status: In Progress

#1424 Introduce `before_send_transaction` option
  CHANGELOG.md
  phpstan-baseline.neon
  src/Client.php
  src/Options.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Type: Feature, Status: In Progress

#1431 docs: Remove changelog entry
  CHANGELOG.md
Labels: Type: Documentation

#1428 fix: Set `traces_sample_rate` to `null` by default
  CHANGELOG.md
  src/Options.php
  src/State/Hub.php
  tests/Tracing/TransactionTest.php
Labels: Type: Bug, Status: Confirmed

#1432 Prepare 3.12.0
  CHANGELOG.md
  composer.json
  phpstan-baseline.neon
  src/Client.php
  src/Options.php
  src/State/Hub.php
  tests/ClientTest.php
  tests/OptionsTest.php
  tests/Tracing/TransactionTest.php
Labels: Type: Documentation
