Repository getsentry/sentry-php, pull requests merged in 2022-10, with the labels that each got.

#1387 meta: Introduce LOGAF
  CONTRIBUTING.md
Labels: Type: Improvement, Status: In Progress

#1389 meta: Check for github-actions updates
  .github/dependabot.yml
Labels: Type: Improvement, Status: In Progress

#1396 feat: Add tracePropagationTargets option
  CHANGELOG.md
  phpstan-baseline.neon
  src/Options.php
  src/Tracing/GuzzleTracingMiddleware.php
  tests/OptionsTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Feature, Status: In Progress

#1394 Prepare release 3.9.0
  CHANGELOG.md
  Makefile
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Client.php
  src/ClientInterface.php
  src/Dsn.php
  src/Event.php
  src/Options.php
  src/Serializer/PayloadSerializer.php
  src/State/Hub.php
  src/State/Scope.php
  src/Tracing/DynamicSamplingContext.php
  src/Tracing/GuzzleTracingMiddleware.php
  src/Tracing/Span.php
  src/Tracing/SpanContext.php
  src/Tracing/Transaction.php
  src/Tracing/TransactionContext.php
  src/Tracing/TransactionMetadata.php
  src/Tracing/TransactionSource.php
  src/Transport/DefaultTransportFactory.php
  src/UserDataBag.php
  tests/ClientTest.php
  tests/DsnTest.php
  tests/EventTest.php
  tests/OptionsTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/State/ScopeTest.php
  tests/Tracing/DynamicSamplingContextTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TransactionContextTest.php
  tests/Tracing/TransactionMetadataTest.php
  tests/Tracing/TransactionSourceTest.php
  tests/Tracing/TransactionTest.php
  tests/UserDataBagTest.php
Labels: Type: Documentation, Status: In Progress

#1397 ref: Add correct never option for max_request_body_size
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  src/Options.php
  tests/Integration/RequestIntegrationTest.php
Labels: Type: Improvement, Status: Confirmed, Type: Deprecation

#1401 fix: Suppress errors on is_callable
  CHANGELOG.md
  src/Serializer/AbstractSerializer.php
Labels: Type: Bug, Status: Confirmed

#1402 Prepare release 3.9.1
  CHANGELOG.md
Labels: Type: Documentation

#1407 Fix sampling decision when parent is sampled
  CHANGELOG.md
  src/State/Hub.php
  tests/Tracing/TransactionTest.php
Labels: Type: Bug, Status: In Progress

#1408 Prepare 3.10.0
  CHANGELOG.md
  composer.json
  src/Integration/RequestIntegration.php
  src/Options.php
  tests/Integration/RequestIntegrationTest.php
Labels: Type: Documentation

#1410 fix: Only include the transaction name to the DSC if it has good quality
  src/Tracing/DynamicSamplingContext.php
  tests/Tracing/DynamicSamplingContextTest.php
Labels: Type: Bug, Status: Confirmed

#1416 ref: Expose the ExceptionMechanism through the event hint
  CHANGELOG.md
  src/Client.php
  src/EventHint.php
  tests/ClientTest.php
  tests/EventHintTest.php
Labels: Type: Improvement, Status: Confirmed

#1421 docs: Fix changelog formatting
  CHANGELOG.md
Labels: Type: Documentation
