Repository getsentry/sentry-php, pull requests merged in 2022-06, with the labels that each got.

#1324 Ability to set or remove single tag in the Event
  CHANGELOG.md
  src/Event.php
  tests/EventTest.php
Labels: Type: Feature, Status: Confirmed

#1330 feat: set monolog.extra
  CHANGELOG.md
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Type: Improvement, Status: Confirmed

#1331 bug: Set sentry-trace header when using tracing middleware
  CHANGELOG.md
  src/Tracing/GuzzleTracingMiddleware.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Bug, Status: Confirmed
