Repository getsentry/sentry-php, pull requests merged in 2022-05, with the labels that each got.

#1306 Fix PHPStan baseline
  phpstan-baseline.neon
Labels: Type: Improvement, Status: Confirmed

#1305 Bump the minimum version of `guzzlehttp/psr7` to avoid `CVE-2022-24775`
  CHANGELOG.md
  composer.json
Labels: Type: Improvement, Status: Confirmed

#1308 chore: Update logo for dark or light theme
  README.md
Labels: Type: Documentation, Status: Confirmed

#1282 Support http_connect_timeout and http_timeout options
  CHANGELOG.md
  phpstan-baseline.neon
  src/HttpClient/HttpClientFactory.php
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Feature, Status: Confirmed

#1315 Remove memory addresses from anonymous class frames
  CHANGELOG.md
  src/FrameBuilder.php
  tests/StacktraceTest.php
Labels: Type: Bug, Status: Confirmed

#1323 Fix PHPStan errors after update to latest version
  phpstan-baseline.neon
  src/FrameBuilder.php
Labels: Type: Improvement, Status: Confirmed

#1321 Add compatibility with monolog v3
  CHANGELOG.md
  composer.json
  phpstan.neon
  psalm-baseline.xml
  src/Monolog/CompatibilityProcessingHandlerTrait.php
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
  tests/Monolog/RecordFactory.php
Labels: Type: Feature, Status: Confirmed
