Repository getsentry/sentry-php, pull requests merged in 2022-01, with the labels that each got.

#1272 Update PHPStan, Psalm and PHP-CS-Fixer to the latest versions
  .github/workflows/static-analysis.yaml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml.dist
  src/Client.php
  src/ClientBuilder.php
  src/Context/OsContext.php
  src/Context/RuntimeContext.php
  src/Dsn.php
  src/ErrorHandler.php
  src/Event.php
  src/Frame.php
  src/FrameBuilder.php
  src/HttpClient/HttpClientFactory.php
  src/Integration/IgnoreErrorsIntegration.php
  src/Integration/IntegrationRegistry.php
  src/Integration/RequestIntegration.php
  src/Integration/TransactionIntegration.php
  src/Serializer/RepresentationSerializer.php
  src/StacktraceBuilder.php
  src/State/Hub.php
  src/State/HubAdapter.php
  src/Tracing/SpanContext.php
  src/Util/JSON.php
  src/functions.php
  tests/Util/JSONTest.php
Labels: Type: Improvement, Status: Confirmed

#1276 Handle autoloaders that throws while serializing a possible callable
  CHANGELOG.md
  src/Serializer/AbstractSerializer.php
  tests/phpt/serialize_broken_class.phpt
  tests/phpt/serialize_callable_that_makes_autoloader_throw.phpt
Labels: Type: Bug, Type: Improvement, Status: Confirmed

#1277 Restrict the installable versions of `PHP-CS-Fixer` to workaround issue FriendsOfPHP/PHP-CS-Fixer#6238
  composer.json
Labels: Type: Improvement, Status: Confirmed

#1280 Serialization of an array of 2 strings that looks like a callable (again)
  CHANGELOG.md
  src/Serializer/AbstractSerializer.php
  tests/phpt/serialize_broken_class.phpt
  tests/phpt/serialize_callable_that_makes_autoloader_throw.phpt
Labels: Type: Bug, Status: Confirmed

#1278 Change withScope to return callback's return value
  CHANGELOG.md
  src/State/Hub.php
  src/State/HubAdapter.php
  src/State/HubInterface.php
  src/functions.php
  tests/FunctionsTest.php
  tests/State/HubAdapterTest.php
  tests/State/HubTest.php
Labels: Type: Improvement, Status: Confirmed

#1244 Set the values specified in the Monolog's context in the extra context of the event
  CHANGELOG.md
  src/Monolog/Handler.php
  tests/Monolog/HandlerTest.php
Labels: Type: Feature, Status: Confirmed
