Repository getsentry/sentry-php, pull requests merged in 2022-09, with the labels that each got.

#1357 ci: Update phpstan-baseline.neon
  phpstan-baseline.neon
Labels: Status: Confirmed, Type: Deprecation

#1356 Release 3.8.0
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
  src/EventId.php
  src/ExceptionDataBag.php
  src/Integration/IntegrationRegistry.php
  src/Monolog/BreadcrumbHandler.php
  src/Tracing/SpanId.php
  src/Tracing/TraceId.php
  src/Util/SentryUid.php
  tests/Integration/IntegrationRegistryTest.php
  tests/Monolog/BreadcrumbHandlerTest.php
  tests/Monolog/RecordFactory.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Util/SentryUidTest.php
  tests/phpt/error_handler_captures_errors_not_silencable_on_php_8_and_up.phpt
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_respects_capture_silenced_errors_option.phpt
  tests/phpt/error_handler_respects_current_error_reporting_level.phpt
  tests/phpt/error_handler_respects_error_types_option_regardless_of_error_reporting.phpt
Labels: Status: Confirmed

#1358 test: Add tests for ExceptionDataBag
  tests/ExceptionDataBagTest.php
Labels: Type: Improvement, Status: Confirmed

#1367 ref: Use constant for the SDK version
  .craft.yml
  CHANGELOG.md
  scripts/bump-version.sh
  src/Client.php
  src/ClientBuilder.php
  src/Event.php
  tests/ClientBuilderTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement, Status: Confirmed

#1370 fix: Do not throw an TypeError on numeric HTTP headers
  CHANGELOG.md
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Type: Bug, Status: Confirmed

#1373 Prepare release 3.8.1
  CHANGELOG.md
Labels: Status: Confirmed

#1374 ref: Use constant for the SDK version
  .craft.yml
  CHANGELOG.md
  scripts/bump-version.sh
  src/Client.php
  src/ClientBuilder.php
  src/Event.php
  tests/ClientBuilderTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Bug, Status: Confirmed

#1375 test: Add tests for ClientBuilder::getOptions
  tests/ClientBuilderTest.php
Labels: Type: Improvement, Status: Confirmed

#1376 Update release 3.8.1
  CHANGELOG.md
Labels: Status: Confirmed

#1378 Expose a function to retrieve the URL of the CSP endpoint
  CHANGELOG.md
  src/Client.php
  src/ClientInterface.php
  src/Dsn.php
  tests/ClientTest.php
  tests/DsnTest.php
Labels: Type: Feature, Status: Confirmed

#1379 test: Check if the correct trace_id is applied to the event context
  tests/State/ScopeTest.php
Labels: Type: Improvement, Status: Confirmed

#1360 feat: Add support for Dynamic Sampling
  CHANGELOG.md
  Makefile
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Event.php
  src/Serializer/PayloadSerializer.php
  src/State/Hub.php
  src/State/Scope.php
  src/Tracing/DynamicSamplingContext.php
  src/Tracing/GuzzleTracingMiddleware.php
  src/Tracing/Span.php
  src/Tracing/SpanContext.php
  src/Tracing/Transaction.php
  src/Tracing/TransactionContext.php
  src/Tracing/TransactionMetadata.php
  src/Tracing/TransactionSource.php
  src/Transport/DefaultTransportFactory.php
  src/UserDataBag.php
  tests/EventTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/Tracing/DynamicSamplingContextTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TransactionContextTest.php
  tests/Tracing/TransactionMetadataTest.php
  tests/Tracing/TransactionSourceTest.php
  tests/Tracing/TransactionTest.php
  tests/UserDataBagTest.php
Labels: Type: Feature, Status: Confirmed

#1382 feat: Add setSource to TransactionContext
  CHANGELOG.md
  src/Tracing/TransactionContext.php
  tests/Tracing/TransactionContextTest.php
Labels: Type: Feature, Status: In Progress
