Repository getsentry/sentry-php, pull requests merged in 2023-10, with the labels that each got.

#1592 Remove `symfony/polyfill-php80`
  composer.json
  src/FrameBuilder.php
  src/Tracing/DynamicSamplingContext.php
  src/Util/PrefixStripper.php
Labels: Type: Improvement

#1589 [4.x] Add a default cURL HTTP client
  composer.json
  phpstan-baseline.neon
  src/Client.php
  src/ClientBuilder.php
  src/ClientBuilderInterface.php
  src/ClientInterface.php
  src/HttpClient/Authentication/SentryAuthentication.php
  src/HttpClient/HttpClient.php
  src/HttpClient/HttpClientFactory.php
  src/HttpClient/HttpClientFactoryInterface.php
  src/HttpClient/HttpClientInterface.php
  src/HttpClient/Plugin/GzipEncoderPlugin.php
  src/HttpClient/Response.php
  src/Options.php
  src/Transport/DefaultTransportFactory.php
  src/Transport/HttpTransport.php
  src/Transport/NullTransport.php
  src/Transport/RateLimiter.php
  src/Transport/Result.php
  src/Transport/ResultStatus.php
  src/Transport/TransportFactoryInterface.php
  src/Transport/TransportInterface.php
  src/Util/Http.php
  tests/ClientBuilderTest.php
  tests/ClientTest.php
  tests/HttpClient/Authentication/SentryAuthenticationTest.php
  tests/HttpClient/HttpClientFactoryTest.php
  tests/HttpClient/Plugin/GzipEncoderPluginTest.php
  tests/OptionsTest.php
  tests/Transport/DefaultTransportFactoryTest.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/NullTransportTest.php
  tests/Transport/RateLimiterTest.php
  tests/Transport/ResultStatusTest.php
  tests/Util/HttpTest.php
  tests/phpt/error_handler_captures_errors_not_silencable_on_php_8_and_up.phpt
  tests/phpt/error_handler_captures_fatal_error.phpt
  tests/phpt/error_handler_respects_capture_silenced_errors_option.phpt
  tests/phpt/error_handler_respects_current_error_reporting_level.phpt
  tests/phpt/error_handler_respects_error_types_option_regardless_of_error_reporting.phpt
  tests/phpt/error_listener_integration_respects_error_types_option.phpt
  tests/phpt/fatal_error_integration_captures_fatal_error.phpt
  tests/phpt/fatal_error_integration_respects_error_types_option.phpt
Labels: Type: Feature, Type: Improvement, Type: Deprecation

#1597 Add symfony/options-resolver 7.0
  composer.json
Labels: Type: Improvement

#1598 Prepare 3.22.0
  CHANGELOG.md
Labels: Type: Documentation

#1594 Remove deprecations
  UPGRADE-4.0.md
  composer.json
  phpstan-baseline.neon
  src/Breadcrumb.php
  src/Client.php
  src/ClientBuilder.php
  src/Dsn.php
  src/Exception/EventCreationException.php
  src/Exception/ExceptionInterface.php
  src/Exception/InvalidArgumentException.php
  src/Integration/IgnoreErrorsIntegration.php
  src/Integration/RequestIntegration.php
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Tracing/SpanContext.php
  src/Tracing/TransactionContext.php
  tests/Benchmark/SpanBench.php
  tests/ClientTest.php
  tests/DsnTest.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
  tests/OptionsTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/TransactionContextTest.php
Labels: Type: Improvement, Type: Deprecation

#1604 [4.x] Ignore #1599 (PHPCS update) in blame view
  .git-blame-ignore-revs
Labels: Type: Improvement

#1605 Fix request fetcher
  composer.json
  src/Integration/RequestFetcher.php
Labels: Type: Bug

#1602 Cleanup some leftover dependecies
  .github/workflows/static-analysis.yaml
  Makefile
  composer.json
  tests/bootstrap.php
Labels: Type: Improvement

#1603 Simplify breadcrumb API
  src/functions.php
Labels: Type: Improvement, Type: Discussion

#1609 Cleanup the DSN
  src/Dsn.php
  src/Util/Http.php
  tests/DsnTest.php
  tests/Util/HttpTest.php
Labels: Type: Improvement

#1611 Update interfaces
  src/ClientInterface.php
  src/State/HubInterface.php
Labels: Type: Improvement

#1612 Refactor the Payloadseralizer
  src/Serializer/PayloadSerializer.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement

#1614 Refactor `tracePropagationTargets`
  src/Options.php
  src/Tracing/GuzzleTracingMiddleware.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Improvement

#1613 New seralizer logic
  src/Serializer/EnvelopItems/CheckInItem.php
  src/Serializer/EnvelopItems/EnvelopeItemInterface.php
  src/Serializer/EnvelopItems/EventItem.php
  src/Serializer/EnvelopItems/ProfileItem.php
  src/Serializer/EnvelopItems/TransactionItem.php
  src/Serializer/PayloadSerializer.php
  src/Serializer/Traits/BreadcrumbSeralizerTrait.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement

#1615 Add HTTP client request body compression
  phpstan-baseline.neon
  src/HttpClient/HttpClient.php
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Improvement

#1616 Remove `EventType::default`
  src/EventType.php
Labels: Type: Improvement

#1617 Add ResponseTest
  tests/HttpClient/ResponseTest.php
Labels: Type: Improvement

#1620 Fix setting cURL request headers
  src/HttpClient/HttpClient.php
  src/Util/Http.php
  tests/Util/HttpTest.php
Labels: Type: Bug
