Repository getsentry/sentry-php, pull requests merged in 2023-05, with the labels that each got.

#1522 ref: Attach the DSC to error events
  src/State/Scope.php
  src/Tracing/DynamicSamplingContext.php
  tests/State/ScopeTest.php
  tests/Tracing/DynamicSamplingContextTest.php
Labels: Type: Improvement

#1523 Prepare 3.18.0
  CHANGELOG.md
Labels: Type: Documentation

#1529 ref: Ignore empty context values
  src/Event.php
  src/State/Scope.php
  tests/State/ScopeTest.php
Labels: Type: Improvement, Status: Confirmed

#1530 Prepare 3.18.1
  CHANGELOG.md
Labels: Type: Documentation

#1534 fix: Require php-http/message-factory
  CHANGELOG.md
  composer.json
Labels: Type: Bug, Status: In Progress

#1542 Use HTTP/1.1 when compression is enabled
  CHANGELOG.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/HttpClient/HttpClientFactory.php
Labels: Type: Bug
