Repository getsentry/sentry-php, pull requests merged in 2023-01, with the labels that each got.

#1441 Fix nullability in getters and setters for traces_sample_rate in Options
  CHANGELOG.md
  phpstan-baseline.neon
  src/Options.php
  src/State/Hub.php
  tests/OptionsTest.php
Labels: Type: Bug, Status: In Progress

#1446 Prepare 3.12.1
  CHANGELOG.md
Labels: Type: Documentation

#1443 feat: add object ID to serialized value
  CHANGELOG.md
  src/Serializer/AbstractSerializer.php
  tests/Serializer/AbstractSerializerTest.php
Labels: Type: Improvement, Status: In Progress

#1455 docs: Remove the need to add Changelogs
  CONTRIBUTING.md
Labels: Type: Documentation, Status: In Progress

#1454 ci: remove danger
  .github/workflows/danger.yml
Labels: Type: Improvement, Status: In Progress

#1451 Log exception's code
  CHANGELOG.md
  src/Client.php
  src/ExceptionMechanism.php
  src/Integration/AbstractErrorListenerIntegration.php
  src/Serializer/PayloadSerializer.php
  tests/ClientTest.php
  tests/ExceptionMechanismTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Feature, Status: Backlog
