Repository getsentry/sentry-php, pull requests merged in 2023-12, with the labels that each got.

#1654 Update UPGRADE-4.0.md
  UPGRADE-4.0.md
Labels: Type: Documentation

#1661 Remove `ClientBuilder` @internal annotation
  src/ClientBuilder.php
Labels: Type: Improvement

#1662 Only apply `sample_rate` to errors/messages
  src/Client.php
Labels: Type: Bug

#1664 Prepare 4.2.0
  CHANGELOG.md
Labels: Type: Documentation

#1663 Disallow to seralize the `HubAdapter`
  src/State/HubAdapter.php
  tests/State/HubAdapterTest.php
Labels: Type: Improvement

#1665 Remove the final keyword from `Hub`, `Client` and `Scope`
  src/Client.php
  src/State/Hub.php
  src/State/Scope.php
Labels: Type: Improvement

#1668 Do not overwrite trace context if already present
  src/State/Scope.php
  tests/State/HubTest.php
Labels: Type: Bug

#1669 Fix not serializing breadcrumbs compatible with Sentry when numeric backed array data is present
  src/Serializer/Traits/BreadcrumbSeralizerTrait.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Bug

#1667 Prepare 4.3.0
  CHANGELOG.md
Labels: Type: Documentation

#1672 Fix tags not being serialized correctly for metrics payload
  src/Serializer/EnvelopItems/MetricsItem.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Bug
