Repository getsentry/sentry-php, pull requests merged in 2023-07, with the labels that each got.

#1559 Compat support for PHPUnit `10`
  src/Integration/FrameContextifierIntegration.php
  tests/BreadcrumbTest.php
  tests/CheckInTest.php
  tests/ClientTest.php
  tests/Context/OsContextTest.php
  tests/DsnTest.php
  tests/EventHintTest.php
  tests/EventIdTest.php
  tests/EventTest.php
  tests/ExceptionDataBagTest.php
  tests/ExceptionMechanismTest.php
  tests/FrameBuilderTest.php
  tests/FrameTest.php
  tests/FunctionsTest.php
  tests/HttpClient/HttpClientFactoryTest.php
  tests/Integration/EnvironmentIntegrationTest.php
  tests/Integration/FrameContextifierIntegrationTest.php
  tests/Integration/IgnoreErrorsIntegrationTest.php
  tests/Integration/IntegrationRegistryTest.php
  tests/Integration/ModulesIntegrationTest.php
  tests/Integration/RequestIntegrationTest.php
  tests/Integration/TransactionIntegrationTest.php
  tests/MonitorConfigTest.php
  tests/MonitorScheduleTest.php
  tests/Monolog/BreadcrumbHandlerTest.php
  tests/Monolog/HandlerTest.php
  tests/OptionsTest.php
  tests/Profiling/ProfileTest.php
  tests/ResponseStatusTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/SeverityTest.php
  tests/StacktraceTest.php
  tests/State/HubAdapterTest.php
  tests/State/HubTest.php
  tests/Tracing/DynamicSamplingContextTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
  tests/Tracing/PropagationContextTest.php
  tests/Tracing/SpanContextTest.php
  tests/Tracing/SpanIdTest.php
  tests/Tracing/SpanStatusTest.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TraceIdTest.php
  tests/Tracing/TransactionContextTest.php
  tests/Tracing/TransactionMetadataTest.php
  tests/Tracing/TransactionTest.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/RateLimiterTest.php
  tests/UserDataBagTest.php
  tests/Util/JSONTest.php
Labels: Type: Improvement

#1561 Undeprecate tags option
  src/Client.php
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Feature, Status: In Progress

#1562 Add the sampling decision to the trace envelope header
  src/Tracing/DynamicSamplingContext.php
  tests/FunctionsTest.php
Labels: Type: Improvement, Status: In Progress

#1568 Strip path prefixes on profile frames
  src/FrameBuilder.php
  src/Profiling/Profile.php
  src/Profiling/Profiler.php
  src/Tracing/Transaction.php
  src/Util/PrefixStripper.php
  tests/Profiling/ProfileTest.php
Labels: Type: Improvement

#1570 Reuse frames in profile
  src/Profiling/Profile.php
  stubs/ExcimerLogEntry.stub
  tests/Profiling/ProfileTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement

#1573 Add captureCheckIn()
  src/State/Hub.php
  src/State/HubAdapter.php
  src/State/HubInterface.php
  src/functions.php
  tests/FunctionsTest.php
  tests/State/HubAdapterTest.php
  tests/State/HubTest.php
Labels: Type: Feature
