Repository getsentry/sentry-php, pull requests merged in 2023-11, with the labels that each got.

#1622 [4.x] Fix fluent return type
  src/Tracing/Span.php
  src/Tracing/SpanContext.php
Labels: Type: Bug

#1624 Handle emtpy DSN
  src/Transport/HttpTransport.php
  src/Transport/NullTransport.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/NullTransportTest.php
Labels: Type: Improvement

#1625 Refactor `logger` option
  phpstan-baseline.neon
  src/Client.php
  src/ClientBuilder.php
  src/Logger/DebugFileLogger.php
  src/Logger/DebugStdOutLogger.php
  src/Options.php
  src/Transport/Result.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Type: Improvement

#1623 Add Request class
  src/HttpClient/HttpClient.php
  src/HttpClient/HttpClientInterface.php
  src/HttpClient/Request.php
  src/Transport/HttpTransport.php
  tests/ClientBuilderTest.php
Labels: Type: Improvement

#1627 Fix invalid option name
  CHANGELOG.md
  UPGRADE-4.0.md
Labels: Type: Documentation

#1628 Add permissions to GitHub actions
  .github/workflows/ci.yml
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
Labels: Type: Improvement

#1626 E2E HTTP client tests
  tests/HttpClient/HttpClientTest.php
  tests/HttpClient/TestServer.php
  tests/testserver/.gitignore
  tests/testserver/index.php
Labels: Type: Improvement

#1630 Drupal integration supports the 4.x SDK
  README.md
Labels: Type: Documentation

#1632 Search for curl_init() only in root namespace
  src/HttpClient/HttpClient.php
Labels: Type: Improvement

#1633 Fix capturing OOM errors when very memory constrained
  .github/workflows/ci.yml
  phpstan-baseline.neon
  phpunit.xml.dist
  src/ErrorHandler.php
  tests/phpt-oom/out_of_memory_fatal_error_increases_memory_limit.phpt
  tests/phpt/error_handler_captures_out_of_memory_fatal_error.phpt
  tests/phpt/error_handler_handles_exception_only_once.phpt
Labels: Type: Improvement

#1641 Add missing `merge_target` to release action
  .github/workflows/publish-release.yaml
Labels: Type: Improvement

#1642 Some cleanup
  .github/workflows/ci.yml
  composer.json
Labels: Type: Improvement

#1644 Normalize response status
  src/Tracing/Span.php
Labels: Type: Improvement

#1647 Add support for Spotlight
  phpstan-baseline.neon
  src/HttpClient/Request.php
  src/Options.php
  src/Spotlight/SpotlightClient.php
  src/Transport/HttpTransport.php
  tests/OptionsTest.php
Labels: Type: Feature
