Repository getsentry/sentry-php, pull requests merged in 2023-02, with the labels that each got.

#1456 Prepare 3.13
  CHANGELOG.md
  composer.json
  src/Client.php
  src/ExceptionMechanism.php
  src/Integration/AbstractErrorListenerIntegration.php
  src/Serializer/AbstractSerializer.php
  src/Serializer/PayloadSerializer.php
  tests/ClientTest.php
  tests/ExceptionMechanismTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Documentation

#1453 fix: Sanatize HTTP client spans & breadcrumbs
  src/Tracing/GuzzleTracingMiddleware.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Bug, Status: In Progress

#1462 fix: set php-http/discovery to allow false
  composer.json
Labels: Type: Bug

#1458 feat: Add enableTracing Option
  phpstan-baseline.neon
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Feature

#1463 ci: Remove --ignore-platform-req=php from PHP 8.2
  .github/workflows/ci.yml
Labels: Type: Improvement

#1465 Prepare 3.13.1
  CHANGELOG.md
Labels: Type: Documentation

#1470 fix: Use array_replace to preserve request body keys
  src/Integration/RequestIntegration.php
  tests/Integration/RequestIntegrationTest.php
Labels: Type: Bug, Status: Confirmed

#1471 Switch to MIT license
  LICENSE
  composer.json
Labels: Type: Documentation

#1483 Prevent calling magic methods to retrieve ID from object
  phpstan-baseline.neon
  src/Serializer/AbstractSerializer.php
  tests/Serializer/AbstractSerializerTest.php
Labels: Type: Improvement, Status: In Progress

#1482 Fix missing deprecation message
  src/Client.php
Labels: Type: Improvement, Type: Documentation, Status: In Progress
