Repository getsentry/sentry-php, pull requests merged in 2023-03, with the labels that each got.

#1489 docs: Add 3.14.0 changelog
  CHANGELOG.md
Labels: Type: Documentation, Status: In Progress

#1488 Prepare 3.14.0
  CHANGELOG.md
  phpstan-baseline.neon
  src/Client.php
  src/Options.php
  src/Serializer/AbstractSerializer.php
  src/Util/JSON.php
  tests/OptionsTest.php
  tests/Serializer/AbstractSerializerTest.php
  tests/Util/JSONTest.php
Labels: Type: Documentation

#1477 feat: Add support for profiling
  phpstan.neon
  psalm-baseline.xml
  psalm.xml.dist
  src/Context/OsContext.php
  src/Event.php
  src/Integration/EnvironmentIntegration.php
  src/Options.php
  src/Profiling/Profile.php
  src/Profiling/Profiler.php
  src/Serializer/PayloadSerializer.php
  src/State/Hub.php
  src/Tracing/Transaction.php
  stubs/ExcimerLog.stub
  stubs/ExcimerLogEntry.stub
  stubs/ExcimerProfiler.stub
  stubs/ExcimerTimer.stub
  stubs/LICENSE
  stubs/autoload.php
  stubs/globals.stub
  tests/Context/OsContextTest.php
  tests/OptionsTest.php
  tests/Profiling/ProfileTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Feature, Status: In Progress

#1492 Prepare 3.15.0
  CHANGELOG.md
Labels: Type: Documentation, Status: In Progress

#1490 Introduce `trace` helper function
  src/functions.php
  tests/FunctionsTest.php
Labels: Type: Feature, Status: In Progress

#1467 feat: Add support for Cron Monitoring
  src/CheckIn.php
  src/CheckInStatus.php
  src/Event.php
  src/EventType.php
  src/Serializer/PayloadSerializer.php
  src/Transport/HttpTransport.php
  tests/CheckInTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Feature, Status: In Progress

#1495 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Documentation

#1500 reaf: Accept check-in duration as float
  src/CheckIn.php
Labels: Type: Improvement, Status: In Progress

#1498 Prepare 3.16.0
  CHANGELOG.md
Labels: Type: Documentation, Status: In Progress

#1504 Use `php-http/discovery": "^1.15`
  composer.json
  src/Integration/RequestFetcher.php
  src/Integration/RequestIntegration.php
Labels: Type: Improvement, Status: In Progress

#1503 feat: Add `ignore_exceptions` & `ignore_transactions`
  phpstan-baseline.neon
  src/Client.php
  src/Integration/IgnoreErrorsIntegration.php
  src/Options.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Type: Feature, Status: In Progress

#1505 Prepare 3.17.0
  CHANGELOG.md
Labels: Type: Documentation
