Repository getsentry/sentry-php, pull requests merged in 2024-05, with the labels that each got.

#1735 Fix missing data on HTTP spans
  src/Tracing/GuzzleTracingMiddleware.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Bug

#1717 Add timing span when emiting a timing metric
  src/Metrics/Metrics.php
Labels: Type: Feature

#1742 Use `AWS_LAMBDA_FUNCTION_VERSION` env var for release if available
  src/Options.php
  tests/OptionsTest.php
Labels: Type: Improvement

#1722 Add error message to failed requests
  src/HttpClient/HttpClient.php
  tests/HttpClient/HttpClientTest.php
  tests/testserver/index.php
Labels: Type: Improvement

#1740 Test span sampled status before creating child spans
  src/Tracing/GuzzleTracingMiddleware.php
  src/functions.php
  tests/FunctionsTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
Labels: Type: Bug

#1745 Type hint `float` on metrics calls
  src/Metrics/Metrics.php
Labels: Type: Improvement

#1741 Represent callable strings as strings
  src/Serializer/AbstractSerializer.php
  tests/Serializer/AbstractSerializerTest.php
Labels: Type: Improvement
