Repository getsentry/sentry-php, pull requests merged in 2024-01, with the labels that each got.

#1676 Do not send an empty event if no metrics are in the bucket
  src/CheckIn.php
  src/Metrics/MetricsAggregator.php
  src/functions.php
Labels: Type: Improvement

#1670 Implement Metrics::timing
  src/Metrics/Metrics.php
  src/Metrics/MetricsAggregator.php
  src/Metrics/Types/AbstractType.php
  tests/Metrics/MetricsTest.php
Labels: Type: Feature

#1679 Add cron monitor wrapper
  src/functions.php
  tests/FunctionsTest.php
Labels: Type: Feature

#1681 Deprecate user segment
  src/Tracing/DynamicSamplingContext.php
  src/UserDataBag.php
  tests/Tracing/DynamicSamplingContextTest.php
Labels: Type: Deprecation

#1683 Rename `$callable` to `$callback`
  src/Metrics/Metrics.php
Labels: Type: Improvement

#1684 Add `TransactionContext::make()` & `SpanContext::make()`
  src/Tracing/SpanContext.php
  src/Tracing/TransactionContext.php
  tests/Tracing/SpanTest.php
  tests/Tracing/TransactionTest.php
Labels: Type: Feature

#1680 Add support for W3C traceparent header
  src/Tracing/GuzzleTracingMiddleware.php
  src/Tracing/PropagationContext.php
  src/Tracing/Span.php
  src/Tracing/TransactionContext.php
  src/functions.php
  tests/FunctionsTest.php
  tests/Tracing/GuzzleTracingMiddlewareTest.php
  tests/Tracing/PropagationContextTest.php
  tests/Tracing/TransactionContextTest.php
Labels: Type: Feature

#1689 Prepare 4.4.0
  CHANGELOG.md
Labels: Type: Documentation

#1690 Add `before_send_check_in` & `before_send_metrics`
  phpstan-baseline.neon
  src/Client.php
  src/Options.php
  tests/ClientTest.php
  tests/OptionsTest.php
Labels: Type: Feature

#1682 Fix `_metrics_summary` formatting
  src/Metrics/MetricsAggregator.php
  src/Serializer/EnvelopItems/TransactionItem.php
  src/Tracing/Span.php
  tests/Metrics/MetricsTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/Tracing/SpanTest.php
Labels: Type: Bug

#1691 Widen logger type hints
  src/Logger/DebugFileLogger.php
  src/Logger/DebugStdOutLogger.php
Labels: Type: Improvement

#1692 Allow whitespace in metric tag values
  src/Serializer/EnvelopItems/MetricsItem.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Bug

#1693 Prepare 4.5.0
  CHANGELOG.md
Labels: Type: Documentation
