Repository getsentry/sentry-php, pull requests merged in 2024-04, with the labels that each got.

#1725 Depreacte `SpanStatus::resourceExchausted()`
  src/Tracing/SpanStatus.php
  tests/Monolog/BreadcrumbHandlerTest.php
  tests/Tracing/SpanStatusTest.php
Labels: Type: Improvement

#1726 Handle `metric_bucket` rate limits
  src/Transport/RateLimiter.php
  tests/Transport/RateLimiterTest.php
Labels: Type: Improvement

#1728 Handle namespaces for `metric_bucket` rate limits
  src/Serializer/EnvelopItems/MetricsItem.php
  src/Transport/HttpTransport.php
  src/Transport/RateLimiter.php
  tests/Transport/HttpTransportTest.php
  tests/Transport/RateLimiterTest.php
Labels: Type: Improvement

#1732 Fix deprecation notice when trying to serialize a callable
  src/Serializer/AbstractSerializer.php
  tests/phpt/test_callable_serialization.phpt
Labels: Type: Bug

#1729 Update metric normalization
  src/Serializer/EnvelopItems/MetricsItem.php
  tests/Serializer/EnvelopeItems/MetricsItemTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement

#1733 Prepare 4.7.0
  CHANGELOG.md
Labels: Type: Documentation
