Repository getsentry/sentry-php, pull requests merged in 2024-11, with the labels that each got.

#1785 Always use `ms` scaled timeouts
  src/HttpClient/HttpClient.php
Labels: Type: Bug

#1760 Testing on PHP 8.4
  .github/workflows/ci.yml
  .github/workflows/static-analysis.yaml
  composer.json
  src/ErrorHandler.php
  src/FrameBuilder.php
  src/Severity.php
  tests/Serializer/AbstractSerializerTest.php
  tests/SeverityTest.php
  tests/phpt/error_handler_respects_error_types_option_regardless_of_error_reporting.phpt
Labels: Type: Improvement

#1786 Remove metrics plumbing and deprecate/no-op public API
  phpstan-baseline.neon
  src/Client.php
  src/Event.php
  src/EventType.php
  src/Integration/FrameContextifierIntegration.php
  src/Metrics/Metrics.php
  src/Metrics/MetricsAggregator.php
  src/Metrics/MetricsUnit.php
  src/Metrics/Types/AbstractType.php
  src/Metrics/Types/CounterType.php
  src/Metrics/Types/DistributionType.php
  src/Metrics/Types/GaugeType.php
  src/Metrics/Types/SetType.php
  src/Options.php
  src/Serializer/EnvelopItems/MetricsItem.php
  src/Serializer/EnvelopItems/TransactionItem.php
  src/Serializer/PayloadSerializer.php
  src/Tracing/Span.php
  src/Tracing/Transaction.php
  src/Transport/RateLimiter.php
  src/functions.php
  tests/ClientTest.php
  tests/Metrics/MetricsTest.php
  tests/Serializer/EnvelopeItems/MetricsItemTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/Tracing/SpanTest.php
  tests/Transport/RateLimiterTest.php
Labels: Type: Deprecation

#1787 Prepare 4.10.0
  CHANGELOG.md
Labels: Type: Documentation
