Repository getsentry/sentry-php, pull requests merged in 2024-02, with the labels that each got.

#1697 Remove final from `Metrics` class
  src/Metrics/Metrics.php
Labels: Type: Improvement

#1699 Lazy initialize default values in client builder
  src/Client.php
  src/ClientBuilder.php
  src/Transport/HttpTransport.php
  tests/ClientBuilderTest.php
Labels: Type: Bug

#1700 Add the SAPI to the runtime context
  src/Context/RuntimeContext.php
  src/Integration/EnvironmentIntegration.php
  src/Profiling/Profile.php
  src/Serializer/EnvelopItems/EventItem.php
  src/Serializer/EnvelopItems/TransactionItem.php
  tests/Context/RuntimeContextTest.php
  tests/Integration/EnvironmentIntegrationTest.php
  tests/Profiling/ProfileTest.php
  tests/Serializer/PayloadSerializerTest.php
Labels: Type: Improvement

#1701 short circuit ignore_exceptions
  src/Client.php
  tests/ClientTest.php
Labels: Type: Improvement

#1678 Log also exception when failed to get source code excerpt
  src/Integration/FrameContextifierIntegration.php
Labels: Type: Improvement

#1703 Prepare 4.6.0
  CHANGELOG.md
Labels: Type: Documentation

#1707 adds `JSON_ERROR_NON_BACKED_ENUM` to allowed `JSON::encode()` errors.
  src/Util/JSON.php
  tests/Util/Fixtures/NonBackedEnum.php
  tests/Util/JSONTest.php
Labels: Type: Improvement
