Repository getsentry/sentry-php, pull requests merged in 2025-08, with the labels that each got.

#1867 Add Monolog Sentry Logs handler
  psalm-baseline.xml
  src/Logs/LogLevel.php
  src/Monolog/CompatibilityLogLevelTrait.php
  src/Monolog/LogsHandler.php
  tests/Monolog/LogsHandlerTest.php
Labels: Feature

#1876 Refactor trace header parsing logic
  phpstan-baseline.neon
  src/Tracing/PropagationContext.php
  src/Tracing/Traits/TraceHeaderParserTrait.php
  src/Tracing/TransactionContext.php
Labels: Improvement

#1882 Fix non string indexed attributes passed as log attributes
  .php-cs-fixer.dist.php
  src/Logs/LogsAggregator.php
  tests/Logs/LogsAggregatorTest.php
Labels: Bug

#1883 Prepare 4.15.0
  CHANGELOG.md
Labels: Documentation
