Repository getsentry/sentry-php, pull requests merged in 2025-05, with the labels that each got.

#1828 Fix stripping prefixes from closure frames
  src/FrameBuilder.php
  tests/FrameBuilderTest.php
Labels: Bug

#1832 Prepare 4.11.1
  CHANGELOG.md
Labels: Documentation

#1835 Fix new phpstan errors
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Serializer/AbstractSerializer.php
Labels: Improvement, PHP

#1834 Add new `strictTracePropagation` option
  phpstan-baseline.neon
  src/Options.php
  src/functions.php
  tests/OptionsTest.php
Labels: Feature

#1836 Log correct source of sampling decision
  src/State/Hub.php
Labels: Bug

#1813 Add Sentry logs
  phpstan-baseline.neon
  src/Attributes/Attribute.php
  src/Attributes/AttributeBag.php
  src/Client.php
  src/Event.php
  src/EventType.php
  src/Logger/DebugFileLogger.php
  src/Logger/DebugLogger.php
  src/Logger/DebugStdOutLogger.php
  src/Logs/Log.php
  src/Logs/LogLevel.php
  src/Logs/Logs.php
  src/Logs/LogsAggregator.php
  src/Options.php
  src/Serializer/EnvelopItems/EnvelopeItemInterface.php
  src/Serializer/EnvelopItems/LogsItem.php
  src/Serializer/EnvelopItems/ProfileItem.php
  src/Serializer/EnvelopItems/TransactionItem.php
  src/Serializer/PayloadSerializer.php
  src/Transport/RateLimiter.php
  src/Util/Arr.php
  src/functions.php
  tests/Attributes/AttributeBagTest.php
  tests/Attributes/AttributeTest.php
  tests/Logs/LogTest.php
  tests/Logs/LogsTest.php
  tests/Serializer/PayloadSerializerTest.php
  tests/Util/ArrTest.php
Labels: Feature
