Repository getsentry/sentry-php, pull requests merged in 2025-09, with the labels that each got.

#1889 Prepare 4.15.2
  CHANGELOG.md
Labels: Documentation

#1905 merge master into 5.x
  .github/workflows/ci.yml
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
  .php-cs-fixer.dist.php
  CHANGELOG-5.0.md
  CHANGELOG.md
  phpstan-baseline.neon
  src/Client.php
  src/Logs/LogsAggregator.php
  src/Monolog/LogsHandler.php
  src/Options.php
  src/Tracing/PropagationContext.php
  src/Tracing/Traits/TraceHeaderParserTrait.php
  src/Tracing/TransactionContext.php
  src/Transport/Result.php
  tests/Logs/LogsAggregatorTest.php
  tests/Monolog/LogsHandlerTest.php
  tests/OptionsTest.php
Labels: 5.x

#1900 ref: use composer to get installed modules
  composer.json
  src/Integration/ModulesIntegration.php
  tests/Integration/ModulesIntegrationTest.php
Labels: 5.x

#1922 ref: remove polyfill
  phpstan-baseline.neon
  psalm.xml.dist
  src/CheckInStatus.php
  src/Dsn.php
  src/Event.php
  src/EventHint.php
  src/EventId.php
  src/EventType.php
  src/FrameBuilder.php
  src/Integration/IntegrationRegistry.php
  src/MonitorScheduleUnit.php
  src/Severity.php
  src/Stacktrace.php
  src/State/Scope.php
  src/Tracing/DynamicSamplingContext.php
  src/Tracing/SpanId.php
  src/Tracing/SpanStatus.php
  src/Tracing/TraceId.php
  src/Tracing/TransactionSource.php
  src/Transport/ResultStatus.php
  src/UserDataBag.php
  src/Util/DebugType.php
  tests/Logs/LogsAggregatorTest.php
  tests/Monolog/LogsHandlerTest.php
Labels: Improvement

#1928 meta: Pin symfony/phpunit-bridge
  composer.json
Labels: dependencies
